/**
 * XAYTHEON - Governance Report Generator
 * 
 * This service transforms raw compliance audit data into professional formats
 * for executive review and auditor submission.
 */

class ReportGeneratorService {
    constructor() {
        this.reportTemplates = {
            EXECUTIVE: 'executive_summary',
            TECHNICAL: 'technical_details',
            AUDITOR: 'certified_disclosure'
        };
    }

    /**
     * Generates a beautifully formatted report based on audit results
     * @param {Object} auditData - Pure data from ComplianceService
     * @param {string} format - 'json' | 'markdown' | 'html'
     * @returns {string|Object} Formatted report
     */
    generateReport(auditData, format = 'json', template = 'EXECUTIVE') {
        console.log(`📊 Generating ${format.toUpperCase()} report for audit: ${auditData.auditId}`);

        switch (format.toLowerCase()) {
            case 'markdown':
                return this.toMarkdown(auditData, template);
            case 'html':
                return this.toHTML(auditData, template);
            case 'json':
            default:
                return this.toJSON(auditData);
        }
    }

    /**
     * Internal: Convert to Markdown
     */
    toMarkdown(data, template) {
        const statusIcon = data.status === 'compliant' ? '✅' : data.status === 'warning' ? '⚠️' : '❌';

        let md = `# Governance & Compliance Report: ${data.repoPath}\n\n`;
        md += `**Status:** ${statusIcon} ${data.status.toUpperCase()}\n`;
        md += `**Score:** ${data.overallScore}/100\n`;
        md += `**Audit ID:** \`${data.auditId}\`\n`;
        md += `**Date:** ${new Date(data.timestamp).toLocaleString()}\n\n`;

        md += `## Summary Statistics\n`;
        md += `- **Frameworks:** ${data.targetFrameworks.join(', ')}\n`;
        md += `- **Total Checks:** ${data.statistics.totalChecks}\n`;
        md += `- **Passed:** ${data.statistics.passedChecks}\n`;
        md += `- **Failed:** ${data.statistics.failedChecks}\n\n`;

        if (data.violations.length > 0) {
            md += `## Critical Violations\n\n`;
            md += `| Framework | Severity | Control | File | Message |\n`;
            md += `|-----------|----------|---------|------|---------|\n`;

            data.violations.forEach(v => {
                const sevIcon = v.severity === 'critical' ? '🔴' : v.severity === 'high' ? '🟠' : '🟡';
                md += `| ${v.framework} | ${sevIcon} ${v.severity} | ${v.control} | \`${v.file}\` | ${v.message} |\n`;
            });

            md += `\n### Recommended Remediation Actions\n\n`;
            data.violations.forEach((v, i) => {
                md += `${i + 1}. **${v.file}**: ${v.remediation}\n`;
            });
        } else {
            md += `## No Violations Found\n\nThe repository adheres to all target controls in the selected frameworks.\n`;
        }

        md += `\n---\n*Generated by Xaytheon Autonomous Governance Engine*`;
        return md;
    }

    /**
     * Internal: Convert to HTML (Used for dashboard preview)
     */
    toHTML(data, template) {
        // Simplified HTML representation
        const statusClass = data.status;
        const scoreColor = data.overallScore > 80 ? '#10b981' : data.overallScore > 50 ? '#f59e0b' : '#ef4444';

        return `
            <div class="report-container">
                <header class="report-header">
                    <h2>Compliance Report - ${data.repoPath}</h2>
                    <div class="status-badge ${statusClass}">${data.status.toUpperCase()}</div>
                </header>
                <section class="score-section">
                    <div class="score-circle" style="border-color: ${scoreColor}">
                        <span class="score-value">${data.overallScore}</span>
                        <span class="score-label">Governance Score</span>
                    </div>
                </section>
                <section class="violations-section">
                    <h3>Identified Vulnerabilities (${data.violations.length})</h3>
                    <ul class="violation-list">
                        ${data.violations.map(v => `
                            <li class="violation-item severity-${v.severity}">
                                <div class="violation-meta">
                                    <span class="framework">${v.framework}</span>
                                    <span class="control">${v.control}</span>
                                </div>
                                <p class="violation-msg"><strong>${v.file}</strong>: ${v.message}</p>
                                <div class="remediation-box">
                                    <strong>Remediation:</strong> ${v.remediation}
                                </div>
                            </li>
                        `).join('')}
                    </ul>
                </section>
            </div>
        `;
    }

    /**
     * Internal: JSON enrichment
     */
    toJSON(data) {
        return {
            meta: {
                generator: "XAYTHEON_GOV_v1.2",
                generated_at: new Date().toISOString()
            },
            report: data
        };
    }
}

module.exports = new ReportGeneratorService();
