const ROLES = {
  ADMIN: "admin",
  MODERATOR: "moderator",
  USER: "user"
};

const PERMISSIONS = {
  CREATE_USER: "create_user",
  DELETE_USER: "delete_user",
  VIEW_REPORTS: "view_reports",
  MANAGE_SETTINGS: "manage_settings",
  CREATE_POST: "create_post",
  DELETE_POST: "delete_post",

  // ADD THESE
  VIEW_HISTORY: "view_history",
  UPDATE_HISTORY: "update_history"
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.DELETE_USER,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.CREATE_POST,
    PERMISSIONS.DELETE_POST,
    PERMISSIONS.VIEW_HISTORY,
    PERMISSIONS.UPDATE_HISTORY
  ],

  [ROLES.MODERATOR]: [
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.DELETE_POST,
    PERMISSIONS.VIEW_HISTORY
  ],

  [ROLES.USER]: [
    PERMISSIONS.CREATE_POST,
    PERMISSIONS.VIEW_HISTORY,
    PERMISSIONS.UPDATE_HISTORY
  ]
};


module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS };

